server:
  port: 8082

spring:
  application:
    name: aithronix-cart

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 5000

jwt:
  secret: your-secret-key-here-make-it-very-long-and-secure-1234567890

